# -*- coding: utf-8 -*-
"""Assignment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FvdIFNR-WimnvA_I_A4pB0cGweeLnfqN
"""

import sqlite3 as sq
conn = sq.connect("wanafunzi.db")
cur = conn.cursor()

StudTable = """
      CREATE TABLE Student_Table (
            studentID TEXT,
            yearJoined INTEGER,
            Title TEXT,
            first_Name TEXT,
            last_Name TEXT,
            class TEXT,
            phone_Number TEXT,
            Email_addr TEXT,
            City TEXT,
            State,
            Country TEXT,
            primary key(studentID)
            )"""
cur.execute(StudTable)
print("The table Students is successfully created.")
conn.commit() # commits to the database
conn.close() # closes the database

import sqlite3, csv 

connection = sqlite3.connect("wanafunzi.db") 
cursor = connection.cursor()

with open('/content/records2 - records2.csv', 'r') as file:
      no_records = 0
      for row in file:
          cursor.execute("INSERT INTO Student_Table VALUES (?,?,?,?,?,?,?,?,?,?,?)", row.split(","))
          connection.commit()
          no_records += 1
connection.close()
print('\n{} Records Transfered'.format(no_records))